project:
  type: website

website:
  title: "Blog-GM-incidencia"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    lang: es
    theme: cosmo
    css: styles.css

editor: visual

