---
title: "Catálogo de Productos en Google Drive"
author: "Miguel Equihua"
date: "2023-12-1"
categories: [conceptos,herramientas]
lang: es
tables: yes
format:
  html:
    toc: true
    toc-title: Contenido
    code-fold: true
---

```{=html}
<!--
TODO  probar relación interactiva con la base de datos
filters:
  - interactive-sql
databases:
  - name: atlas-y-cat.db
    path: "./"

-->
```
```{r}
#| label: inicio
#| echo: false
#| message: false
#| warning: false
#| include: false
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(googledrive))
suppressPackageStartupMessages(library(googlesheets4))
library(readxl)
#library(knitr)
#library(kableExtra)
library(flextable)
library(igraph)
library(DBI)
library(RSQLite)
library(reticulate)
```


La aplicación para operar rutinaria y automáticamente con Google Drive para registrar en una base de datos SQLite los productos contenidos de los Pronaii ya está lista.


```{r}
#| label: control_db
#| echo: false
#| message: false

# Autenticación genérica
suppressMessages(drive_auth(email = TRUE))

# localiza la carpeta PRONACES SSyS
atlas_dir <- drive_find(n_max = 10, type = "folder", 
                       pattern = "0-control-atlas-catalogo")

# Contenido de la carpeta de Control del Atlas
atlas_contet <- drive_ls(path = atlas_dir$id)
drive_download(atlas_contet$id[1], "./atlas-y-cat.db", overwrite = TRUE)

doc_interes <- atlas_contet$id[grepl("\\.db$", atlas_contet$name)]

url_db <- paste0("https://drive.google.com/file/d/", doc_interes)

con_datos <- dbConnect(drv = SQLite(), dbname = "atlas-y-cat.db")

```

Ahora podemos ver la lista de tablas que tiene la base de datos.

```{r}
#| label: tablas_control
#| echo: false
#| message: false
#| tbl-cap: Lista de tablas de control en la base de datos

# Show List of Tables
data.frame(tabla = dbListTables(con_datos)) %>%
  flextable(cwidth = 3) %>% 
  set_header_labels(values = list(tabla = "tabla")) %>% 
  theme_zebra()
```

¿Qué proyectos hay en el *atlas-catálogo*?

```{r}
#| label: reg_pronaii
#| echo: false
#| message: false
#| tbl-cap: Proyectos registrados en Google Drive

# Get table
dbReadTable(con_datos, 'drive_folders') %>% 
  select(name, id) %>% 
  filter(!(grepl("0-control|Materiales para", name))) %>% 
  mutate(id = str_replace(id, "(?<=.{4})(.*)", "********")) %>% 
  flextable() %>% 
  set_header_labels(values = list(name = "Pronaii", id = "GoDr id")) %>% 
  width(c(1,2), width = c(7,3), unit = "cm") %>% 
  theme_zebra()

```

Ahora, veamos cuántos documentos hay en cada uno de estos proyectos.

```{r}
#| label: num_docs_pronaii
#| echo: false
#| message: false
#| tbl-cap: Numero de productos por Pronaii en Google Drive

dbReadTable(con_datos, "drive_folders") %>%
      filter(!grepl("0-control|Materiales para", name)) %>%
      select(id, name) %>% 
      full_join(dbReadTable(con_datos, "drive_files"), 
                 by = join_by(id == X_parent), suffix = c("", ".file")) %>% 
      select(id, name, name.file) %>% 
      group_by(name) %>% 
      summarise(docs = sum(!is.na(name.file), na.rm = TRUE)) %>% 
      filter(!is.na(name)) %>%
      flextable() %>% 
      set_header_labels(values = list(name = "Pronaii", docs = "Num docs")) %>% 
      width(c(1,2), width = c(7,3), unit = "cm") %>% 
      theme_zebra()

```
